In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
# sentence
sent=['the glass of milk',
      'the glass of juice',
      'i am a good boy',
      'i am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define the vocabulary size
voc_size=10000

In [5]:
# one hot representation 
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[1060, 407, 5681, 7348],
 [1060, 407, 5681, 316],
 [8405, 3895, 1025, 5423, 9438],
 [8405, 3895, 1025, 5423, 4897],
 [3158, 1060, 7203, 5681, 4022],
 [9432, 512, 5864, 5423]]

In [7]:
# one embedding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1060  407 5681 7348]
 [   0    0    0    0 1060  407 5681  316]
 [   0    0    0 8405 3895 1025 5423 9438]
 [   0    0    0 8405 3895 1025 5423 4897]
 [   0    0    0 3158 1060 7203 5681 4022]
 [   0    0    0    0 9432  512 5864 5423]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 168ms/step


array([[[ 0.04269189, -0.03081121, -0.0281792 , -0.02939758,
          0.03157667,  0.02928975,  0.00829796,  0.03939376,
         -0.0121126 , -0.0149411 ],
        [ 0.04269189, -0.03081121, -0.0281792 , -0.02939758,
          0.03157667,  0.02928975,  0.00829796,  0.03939376,
         -0.0121126 , -0.0149411 ],
        [ 0.04269189, -0.03081121, -0.0281792 , -0.02939758,
          0.03157667,  0.02928975,  0.00829796,  0.03939376,
         -0.0121126 , -0.0149411 ],
        [ 0.04269189, -0.03081121, -0.0281792 , -0.02939758,
          0.03157667,  0.02928975,  0.00829796,  0.03939376,
         -0.0121126 , -0.0149411 ],
        [-0.01176656,  0.03145399,  0.02193153, -0.00117056,
          0.01346562,  0.02594158, -0.04159005, -0.01731541,
          0.03859648, -0.03815176],
        [ 0.0267624 , -0.03059032,  0.01832763, -0.01561447,
         -0.04198014,  0.03166061, -0.0070595 , -0.02523791,
         -0.03915358, -0.02461535],
        [ 0.03266318,  0.01141731,  0.00746862,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1060,  407, 5681, 7348])

In [21]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 44ms/step


array([[ 0.04269189, -0.03081121, -0.0281792 , -0.02939758,  0.03157667,
         0.02928975,  0.00829796,  0.03939376, -0.0121126 , -0.0149411 ],
       [ 0.04269189, -0.03081121, -0.0281792 , -0.02939758,  0.03157667,
         0.02928975,  0.00829796,  0.03939376, -0.0121126 , -0.0149411 ],
       [ 0.04269189, -0.03081121, -0.0281792 , -0.02939758,  0.03157667,
         0.02928975,  0.00829796,  0.03939376, -0.0121126 , -0.0149411 ],
       [ 0.04269189, -0.03081121, -0.0281792 , -0.02939758,  0.03157667,
         0.02928975,  0.00829796,  0.03939376, -0.0121126 , -0.0149411 ],
       [-0.01176656,  0.03145399,  0.02193153, -0.00117056,  0.01346562,
         0.02594158, -0.04159005, -0.01731541,  0.03859648, -0.03815176],
       [ 0.0267624 , -0.03059032,  0.01832763, -0.01561447, -0.04198014,
         0.03166061, -0.0070595 , -0.02523791, -0.03915358, -0.02461535],
       [ 0.03266318,  0.01141731,  0.00746862,  0.03199797, -0.00777893,
         0.03498054, -0.03784344,  0.04961723